/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccidentIncidentReport {
  actions_taken: string | null;
  activity: string | null;
  affected_contact: string | null;
  affected_is_minor: Generated<boolean>;
  affected_name: string | null;
  affected_relationship: string | null;
  body_parts_affected: string | null;
  closed_at: Timestamp | null;
  closure_reason: string | null;
  created_at: Generated<Timestamp>;
  declaration_confirmed: boolean;
  description: string;
  first_aid_details: string | null;
  first_aid_given: Generated<boolean>;
  first_aider_name: string | null;
  id: string;
  immediate_actions: string | null;
  incident_type: string;
  injury_occurred: Generated<boolean>;
  injury_severity: string | null;
  internal_notes: string | null;
  location: string;
  medical_treatment_required: Generated<boolean>;
  nature_of_injury: string | null;
  occurred_at: Timestamp;
  owner_user_id: string | null;
  prefers_no_contact: Generated<boolean>;
  reporter_email: string;
  reporter_name: string;
  reporter_phone: string | null;
  reporter_relationship: string;
  riddor_reported_at: Timestamp | null;
  riddor_required: boolean | null;
  safeguarding_discussed: Generated<boolean>;
  safeguarding_discussed_at: Timestamp | null;
  safeguarding_notes: string | null;
  severity: string | null;
  status: Generated<string>;
  target_completion_date: Timestamp | null;
  updated_at: Generated<Timestamp>;
  witnesses: string | null;
}

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Timestamp;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface AvailabilityAssignment {
  availability_fixture_id: string;
  created_at: Generated<string>;
  id: string;
  member_id: string | null;
  player_name: string;
  position: number;
}

export interface AvailabilityFixture {
  availability_request_id: string;
  competition_name: string | null;
  competition_type: string | null;
  id: string;
  is_home: boolean;
  match_date: string;
  match_time: string | null;
  opposition: string;
  play_cricket_match_id: string;
  play_cricket_team_id: string;
}

export interface AvailabilityRequest {
  created_at: Generated<string>;
  created_by: string;
  date_from: string;
  date_to: string;
  id: string;
  status: Generated<string>;
  user_group_id: string | null;
}

export interface AvailabilityResponse {
  availability_request_id: string;
  created_at: Generated<string>;
  id: string;
  match_date: string;
  member_id: string;
  note: string | null;
  overridden_by: string | null;
  status: string;
  updated_at: Generated<string>;
}

export interface Charge {
  amount_pence: number;
  charge_date: string;
  created_at: Generated<string>;
  created_by: string;
  deleted_at: string | null;
  deleted_by: string | null;
  deleted_reason: string | null;
  description: string;
  id: string;
  member_id: string;
  original_amount_pence: number | null;
  paid_at: string | null;
  payment_confirmed_at: string | null;
  payment_method: string | null;
  relief_grant_id: string | null;
  relieved_at: string | null;
  relieved_by: string | null;
  relieved_reason: string | null;
  source: Generated<string>;
  stripe_payment_intent_id: string | null;
  type: Generated<string>;
}

export interface ChargeDependent {
  charge_id: string;
  dependent_id: string;
}

export interface ContactSubmission {
  created_at: Generated<string>;
  email: string;
  id: string;
  message: string;
  name: string;
  page: string;
}

export interface Dependent {
  alt_contact_name: string | null;
  alt_contact_phone: string | null;
  alt_contact_whatsapp_consent: boolean | null;
  created_at: Generated<string>;
  data_protection_consent: boolean | null;
  disability_type: string | null;
  dob: string;
  emergency_medical_consent: boolean | null;
  gp_phone: string | null;
  gp_surgery: string | null;
  has_disability: boolean | null;
  id: string;
  medical_fitness_declaration: boolean | null;
  medical_info: string | null;
  member_id: string;
  name: string;
  photo_consent: boolean | null;
  play_cricket_id: string | null;
  played_before: boolean | null;
  previous_cricket: string | null;
  school_year: string | null;
  sex: string;
  user_id: string | null;
  whatsapp_consent: boolean | null;
}

export interface Document {
  archived_at: string | null;
  created_at: Generated<string>;
  created_by: string;
  history: Generated<Json>;
  id: string;
  s3_key: string;
  title: string;
  updated_at: Generated<string>;
  updated_by: string;
  version: Generated<number>;
}

export interface DocumentAssignment {
  assigned_at: Generated<string>;
  assigned_by: string;
  confirmed_at: string | null;
  confirmed_version: number | null;
  document_id: string;
  id: string;
  user_id: string;
}

export interface EventSubscriber {
  email: string;
  id: string;
  meta: Json;
}

export interface FantasyChaosWeek {
  created_at: Generated<string>;
  description: string;
  email_sent: Generated<boolean>;
  gameweek_id: number;
  id: Generated<number>;
  name: string;
  rule_config: Generated<string>;
  rule_type: string;
  season: string;
  send_email: Generated<boolean>;
}

export interface FantasyChipUsage {
  chip_type: string;
  created_at: Generated<string>;
  fantasy_team_id: number;
  gameweek_id: number;
  id: Generated<number>;
  season: string;
}

export interface FantasyPlayer {
  created_at: Generated<string>;
  eligible: Generated<boolean>;
  play_cricket_id: string;
  player_name: string;
  sandwich_cost: Generated<number>;
}

export interface FantasyPlayerScore {
  batting_points: Generated<number>;
  bowling_points: Generated<number>;
  catches: Generated<number>;
  created_at: Generated<string>;
  fielding_points: Generated<number>;
  gameweek_id: number;
  id: Generated<number>;
  is_actual_keeper: Generated<boolean>;
  match_id: string;
  play_cricket_id: string;
  season: string;
  stumpings: Generated<number>;
  team_points: Generated<number>;
  total_points: Generated<number>;
}

export interface FantasyTeam {
  created_at: Generated<string>;
  id: Generated<number>;
  season: string;
  user_id: string;
}

export interface FantasyTeamPlayer {
  fantasy_team_id: number;
  gameweek_added: number;
  gameweek_removed: number | null;
  id: Generated<number>;
  is_captain: Generated<boolean>;
  is_wicketkeeper: Generated<boolean>;
  play_cricket_id: string;
  slot_type: Generated<string>;
}

export interface FantasyTeamScore {
  created_at: Generated<string>;
  fantasy_team_id: number;
  gameweek_id: number;
  id: Generated<number>;
  season: string;
  total_points: Generated<number>;
}

export interface FinancialReliefEvent {
  actor_user_id: string;
  created_at: Generated<Timestamp>;
  event_type: string;
  from_status: string | null;
  id: string;
  note: string | null;
  request_id: string;
  to_status: string | null;
}

export interface FinancialReliefGrant {
  admin_notes: string | null;
  closed_at: Timestamp | null;
  closed_by: string | null;
  closed_reason: string | null;
  covers_match_fees: boolean;
  covers_membership: boolean;
  decided_at: Generated<Timestamp>;
  decided_by: string;
  decision: string;
  effective_from: Timestamp;
  effective_to_exclusive: Timestamp | null;
  id: string;
  member_facing_note: string | null;
  member_id: string;
  membership_partial_pence: number | null;
  request_id: string;
}

export interface FinancialReliefRequest {
  contact_preference: string;
  contribution_ability: string | null;
  contribution_amount_pence: number | null;
  created_at: Generated<Timestamp>;
  declaration_confirmed_at: Timestamp;
  duration: string | null;
  duration_other_text: string | null;
  id: string;
  member_id: string;
  partial_amount_pence: number | null;
  privacy_acknowledged_at: Timestamp;
  reason_category: string | null;
  reason_text: string | null;
  requested_match_fees: boolean;
  requested_membership_full: boolean;
  requested_membership_partial: boolean;
  status: Generated<string>;
  submitted_by_user_id: string;
  updated_at: Generated<Timestamp>;
  volunteer_notes: string | null;
  volunteer_options: Generated<Json>;
  withdrawn_at: Timestamp | null;
  withdrawn_reason: string | null;
}

export interface GameScore {
  best_streak: number;
  catches: number;
  game: Generated<string>;
  id: string;
  level: number;
  score: number;
  updated_at: string;
  user_id: string;
}

export interface GameSponsorship {
  amount_pence: number;
  approved: Generated<boolean>;
  created_at: Generated<string>;
  display_name: string | null;
  game_id: string;
  id: string;
  notes: string | null;
  paid_at: string | null;
  sponsor_email: string;
  sponsor_logo_url: string | null;
  sponsor_message: string | null;
  sponsor_name: string;
  sponsor_phone: string | null;
  sponsor_website: string | null;
  stripe_payment_intent_id: string | null;
}

export interface JuniorTeam {
  age_group: string;
  created_at: Generated<string>;
  id: string;
  name: string;
  sex: string;
}

export interface JuniorTeamManager {
  junior_team_id: string;
  user_id: string;
}

export interface Lead {
  attribution: Json | null;
  consent_ad_storage: Generated<string>;
  consent_ad_user_data: Generated<string>;
  consent_recorded_at: string | null;
  consent_version: string | null;
  created_at: Generated<string>;
  email: string;
  first_campaign_id: string | null;
  first_segment: string | null;
  id: string;
  member_id: string | null;
  name: string | null;
  notes: string | null;
  phone: string | null;
  source: string;
  /**
   * Denormalised from marketing_event; event rows are the source of truth.
   */
  status: Generated<string>;
  updated_at: string | null;
}

export interface MarketingEvent {
  ads_conversion_action: string | null;
  attribution: Json | null;
  campaign_id: string | null;
  created_at: Generated<string>;
  created_by: string | null;
  currency: string | null;
  id: string;
  lead_id: string | null;
  payload: Json | null;
  segment: string | null;
  source: string;
  type: string;
  user_id: string | null;
  value_pence: number | null;
}

export interface MarketingOutbox {
  attempts: Generated<number>;
  created_at: Generated<string>;
  destination: string;
  event_id: string;
  id: string;
  last_error: string | null;
  next_attempt_at: Generated<string>;
  status: Generated<string>;
  succeeded_at: string | null;
}

export interface MatchBall {
  ball_no: number;
  ball_no_disp: number;
  ball_offset_seconds: number | null;
  ball_spot_x: number | null;
  ball_spot_y: number | null;
  ball_time_utc: Timestamp | null;
  batter_ns_rv_id: number | null;
  batter_rv_id: number | null;
  bowler_rv_id: number | null;
  created_at: Generated<Timestamp>;
  dismissed_batter_rv_id: number | null;
  extras_type: string | null;
  highlight_events: Generated<Json>;
  id: Generated<string>;
  innings_number: number;
  l_desc: string;
  match_id: string;
  over_no: number;
  runs_bat: number;
  runs_extra: number;
  rv_match_id: string;
  rv_result_id: string;
  s_desc: string;
  shot_angle: number | null;
  shot_length: number | null;
}

export interface Matchday {
  cancelled_at: string | null;
  cancelled_by: string | null;
  cancelled_reason: string | null;
  competition_type: string | null;
  confirmed_at: string | null;
  confirmed_by: string | null;
  created_at: Generated<string>;
  created_by: string;
  finished_at: string | null;
  finished_by: string | null;
  id: string;
  match_date: string;
  opposition: string;
  play_cricket_match_id: string | null;
  play_cricket_team_id: string;
  result_confirmed_at: string | null;
  result_confirmed_by: string | null;
  result_source: string | null;
  result_type: string | null;
  status: Generated<string>;
}

export interface MatchdayExpense {
  amount_pence: number;
  approved_at: string | null;
  approved_by: string | null;
  created_at: Generated<string>;
  created_by: string;
  description: string | null;
  expense_type: string;
  id: string;
  matchday_id: string;
  receipt_image_url: string | null;
  reimbursed_at: string | null;
  reimbursed_by: string | null;
  rejected_reason: string | null;
  status: Generated<string>;
  submitted_at: string | null;
}

export interface MatchdayPlayer {
  charge_id: string | null;
  created_at: Generated<string>;
  id: string;
  is_captain: Generated<boolean>;
  is_wicketkeeper: Generated<boolean>;
  matchday_id: string;
  member_id: string | null;
  player_name: string;
  replaced_by_matchday_player_id: string | null;
  status: Generated<string>;
}

export interface MatchFeeRate {
  amount_pence: number;
  competition_type: string | null;
  created_at: Generated<string>;
  id: string;
  member_category: string;
  play_cricket_team_id: string | null;
}

export interface MatchPerformanceBatting {
  balls: Generated<number>;
  competition_type: Generated<string>;
  created_at: Generated<string>;
  fours: Generated<number>;
  how_out: Generated<string>;
  id: string;
  match_date: string;
  match_id: string;
  not_out: Generated<boolean>;
  player_id: string;
  player_name: string;
  runs: Generated<number>;
  season: number;
  sixes: Generated<number>;
  team_id: string;
}

export interface MatchPerformanceBowling {
  competition_type: Generated<string>;
  created_at: Generated<string>;
  id: string;
  maidens: Generated<number>;
  match_date: string;
  match_id: string;
  no_balls: Generated<number>;
  overs: Generated<string>;
  player_id: string;
  player_name: string;
  runs: Generated<number>;
  season: number;
  team_id: string;
  wickets: Generated<number>;
  wides: Generated<number>;
}

export interface MatchPerformanceFielding {
  catches: Generated<number>;
  competition_type: Generated<string>;
  created_at: Generated<string>;
  id: string;
  is_wicketkeeper: Generated<boolean>;
  match_date: string;
  match_id: string;
  player_id: string;
  player_name: string;
  run_outs: Generated<number>;
  season: number;
  stumpings: Generated<number>;
  team_id: string;
}

export interface MatchResult {
  away_club_id: string | null;
  away_club_name: string | null;
  away_team_id: string;
  away_team_name: string;
  competition_type: Generated<string>;
  created_at: Generated<string>;
  home_club_id: string | null;
  home_club_name: string | null;
  home_team_id: string;
  home_team_name: string;
  id: string;
  match_date: string;
  match_id: string;
  result: Generated<string>;
  result_applied_to: Generated<string>;
  result_description: Generated<string>;
  season: number;
}

export interface MatchStream {
  created_at: Generated<Timestamp>;
  description: string | null;
  frogbox_stream_id: string;
  id: Generated<string>;
  match_id: string;
  publish_status_id: number | null;
  recording_started_utc: Timestamp | null;
  rv_match_id: string;
  rv_stream_id: number;
  start_utc: Timestamp | null;
  stream_provider_id: number;
  video_id: string;
}

export interface Member {
  address: string | null;
  deleted_at: string | null;
  deleted_by: string | null;
  deleted_reason: string | null;
  dob: string | null;
  email: string | null;
  emergency_contact_name: string | null;
  emergency_contact_telephone: string | null;
  id: string;
  member_category: string | null;
  name: string | null;
  play_cricket_id: string | null;
  postcode: string | null;
  slug: string | null;
  stripe_customer_id: string | null;
  telephone: string | null;
  title: string | null;
}

export interface MemberParentLink {
  created_at: Generated<string>;
  created_by: string | null;
  member_id: string;
  parent_member_id: string;
}

export interface Membership {
  created_at: Generated<string>;
  dependent_id: string | null;
  id: string;
  member_id: string;
  paid_until: string;
  type: string | null;
}

export interface Passkey {
  backedUp: boolean;
  counter: number;
  createdAt: Timestamp | null;
  credentialID: string;
  deviceType: string;
  id: string;
  name: string | null;
  publicKey: string;
  transports: string | null;
  userId: string;
}

export interface PlayCricketMatchCache {
  data: string;
  fetched_at: string;
  match_date: string;
  match_id: string;
}

export interface PlayCricketSyncLog {
  completed_at: string | null;
  errors: string | null;
  id: string;
  matches_processed: Generated<number>;
  season: number;
  started_at: string;
}

export interface PlayCricketTeam {
  created_at: Generated<string>;
  id: string;
  is_junior: Generated<boolean>;
  last_updated: string | null;
  name: string;
  site_id: string;
}

export interface PlayerSponsorship {
  amount_pence: number;
  approved: Generated<boolean>;
  created_at: Generated<string>;
  display_name: string | null;
  id: string;
  notes: string | null;
  paid_at: string | null;
  player_name: string;
  season: number;
  slug: string | null;
  sponsor_email: string;
  sponsor_logo_url: string | null;
  sponsor_message: string | null;
  sponsor_name: string;
  sponsor_phone: string | null;
  sponsor_website: string | null;
  stripe_payment_intent_id: string | null;
}

export interface RvPlayerMapping {
  created_at: Generated<Timestamp>;
  last_seen_match_date: string;
  pc_player_id: string;
  player_name: string;
  rv_player_id: number;
  updated_at: Generated<Timestamp>;
}

export interface ScoutAttachment {
  content_hash: string | null;
  content_type: string;
  created_at: Generated<Timestamp>;
  derived_text: string | null;
  filename: string;
  id: Generated<string>;
  kind: string;
  pending_key: string | null;
  processing_error: string | null;
  processing_state: string;
  s3_key: string | null;
  size_bytes: number;
  thread_id: string;
  user_id: string;
}

export interface ScoutAttachmentCache {
  content_hash: string;
  created_at: Generated<Timestamp>;
  derived_text: string;
  kind: string;
  source: string;
}

export interface ScoutFact {
  confidence: Generated<number>;
  content: string;
  created_at: Generated<Timestamp>;
  embedding: string;
  id: Generated<string>;
  permanence: string | null;
  scope: string;
  source_kb_chunk_id: string | null;
  source_message_id: string | null;
  source_thread_id: string | null;
  superseded_by: string | null;
  tags: Generated<Json>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ScoutKbChunk {
  chunk_index: number;
  content: string;
  created_at: Generated<Timestamp>;
  document_id: string;
  embedding: string;
  id: Generated<string>;
  page_end: number | null;
  page_start: number | null;
  tags: Generated<Json>;
}

export interface ScoutKbDocument {
  chunk_count: Generated<number>;
  content_hash: string | null;
  content_type: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  error_message: string | null;
  filename: string;
  id: Generated<string>;
  kind: string;
  page_count: number | null;
  pending_key: string | null;
  s3_key: string | null;
  size_bytes: number;
  status: string;
  tags: Generated<Json>;
  title: string;
  updated_at: Generated<Timestamp>;
  uploaded_by: string | null;
}

export interface ScoutMember {
  dob: string | null;
  first_membership_at: string | null;
  id: string | null;
  latest_paid_until: string | null;
  member_category: string | null;
  membership_count: Int8 | null;
  name: string | null;
  play_cricket_id: string | null;
  slug: string | null;
}

export interface ScoutMessage {
  attachment_ids: string[] | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  parts: Json;
  role: string;
  thread_id: string;
  token_cache_creation: number | null;
  token_cache_read: number | null;
  token_input: number | null;
  token_output: number | null;
}

export interface ScoutReport {
  cancel_requested: Generated<boolean>;
  competition: string | null;
  created_at: Generated<Timestamp>;
  error_message: string | null;
  file_size_bytes: number | null;
  home_away: string | null;
  id: Generated<string>;
  intent: string | null;
  match_date: string | null;
  match_id: string | null;
  opposition: string | null;
  our_team: string | null;
  s3_key: string | null;
  started_at: Timestamp | null;
  status: Generated<string>;
  thread_id: string;
  title: string;
  user_id: string;
}

export interface ScoutThread {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  mode: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ScoutThreadShare {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  shared_by_user_id: string;
  shared_with_user_id: string;
  thread_id: string;
}

export interface ScoutToolCache {
  cache_key: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  payload: Json;
  tool_name: string;
}

export interface Session {
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface StripeWebhookEvent {
  attempts: Generated<number>;
  id: string;
  processed_at: Timestamp | null;
  received_at: Generated<Timestamp>;
  type: string;
}

export interface TeamOfficial {
  play_cricket_team_id: string;
  user_id: string;
}

export interface TwoFactor {
  backupCodes: string;
  id: string;
  secret: string;
  userId: string;
}

export interface User {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Timestamp;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  role: string | null;
  twoFactorEnabled: boolean | null;
  updatedAt: Timestamp;
}

export interface UserGroup {
  created_at: Generated<Timestamp>;
  created_by_user_id: string | null;
  description: string | null;
  id: string;
  name: string;
}

export interface UserGroupMember {
  added_at: Generated<Timestamp>;
  added_by_user_id: string | null;
  group_id: string;
  member_id: string;
}

export interface Verification {
  createdAt: Timestamp | null;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Timestamp | null;
  value: string;
}

export interface DB {
  accident_incident_report: AccidentIncidentReport;
  account: Account;
  availability_assignment: AvailabilityAssignment;
  availability_fixture: AvailabilityFixture;
  availability_request: AvailabilityRequest;
  availability_response: AvailabilityResponse;
  charge: Charge;
  charge_dependent: ChargeDependent;
  contact_submission: ContactSubmission;
  dependent: Dependent;
  document: Document;
  document_assignment: DocumentAssignment;
  event_subscriber: EventSubscriber;
  fantasy_chaos_week: FantasyChaosWeek;
  fantasy_chip_usage: FantasyChipUsage;
  fantasy_player: FantasyPlayer;
  fantasy_player_score: FantasyPlayerScore;
  fantasy_team: FantasyTeam;
  fantasy_team_player: FantasyTeamPlayer;
  fantasy_team_score: FantasyTeamScore;
  financial_relief_event: FinancialReliefEvent;
  financial_relief_grant: FinancialReliefGrant;
  financial_relief_request: FinancialReliefRequest;
  game_score: GameScore;
  game_sponsorship: GameSponsorship;
  junior_team: JuniorTeam;
  junior_team_manager: JuniorTeamManager;
  lead: Lead;
  marketing_event: MarketingEvent;
  marketing_outbox: MarketingOutbox;
  match_ball: MatchBall;
  match_fee_rate: MatchFeeRate;
  match_performance_batting: MatchPerformanceBatting;
  match_performance_bowling: MatchPerformanceBowling;
  match_performance_fielding: MatchPerformanceFielding;
  match_result: MatchResult;
  match_stream: MatchStream;
  matchday: Matchday;
  matchday_expense: MatchdayExpense;
  matchday_player: MatchdayPlayer;
  member: Member;
  member_parent_link: MemberParentLink;
  membership: Membership;
  passkey: Passkey;
  play_cricket_match_cache: PlayCricketMatchCache;
  play_cricket_sync_log: PlayCricketSyncLog;
  play_cricket_team: PlayCricketTeam;
  player_sponsorship: PlayerSponsorship;
  rv_player_mapping: RvPlayerMapping;
  scout_attachment: ScoutAttachment;
  scout_attachment_cache: ScoutAttachmentCache;
  scout_fact: ScoutFact;
  scout_kb_chunk: ScoutKbChunk;
  scout_kb_document: ScoutKbDocument;
  scout_member: ScoutMember;
  scout_message: ScoutMessage;
  scout_report: ScoutReport;
  scout_thread: ScoutThread;
  scout_thread_share: ScoutThreadShare;
  scout_tool_cache: ScoutToolCache;
  session: Session;
  stripe_webhook_event: StripeWebhookEvent;
  team_official: TeamOfficial;
  twoFactor: TwoFactor;
  user: User;
  user_group: UserGroup;
  user_group_member: UserGroupMember;
  verification: Verification;
}
