/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Timestamp;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface AvailabilityAssignment {
  availability_fixture_id: string;
  created_at: Generated<string>;
  id: string;
  member_id: string | null;
  player_name: string;
  position: number;
}

export interface AvailabilityFixture {
  availability_request_id: string;
  competition_name: string | null;
  competition_type: string | null;
  id: string;
  is_home: boolean;
  match_date: string;
  match_time: string | null;
  opposition: string;
  play_cricket_match_id: string;
  play_cricket_team_id: string;
}

export interface AvailabilityRequest {
  created_at: Generated<string>;
  created_by: string;
  date_from: string;
  date_to: string;
  id: string;
  status: Generated<string>;
}

export interface AvailabilityResponse {
  availability_request_id: string;
  created_at: Generated<string>;
  id: string;
  match_date: string;
  member_id: string;
  note: string | null;
  overridden_by: string | null;
  status: string;
  updated_at: Generated<string>;
}

export interface Charge {
  amount_pence: number;
  charge_date: string;
  created_at: Generated<string>;
  created_by: string;
  deleted_at: string | null;
  deleted_by: string | null;
  deleted_reason: string | null;
  description: string;
  id: string;
  member_id: string;
  paid_at: string | null;
  payment_confirmed_at: string | null;
  payment_method: string | null;
  source: Generated<string>;
  stripe_payment_intent_id: string | null;
  type: Generated<string>;
}

export interface ChargeDependent {
  charge_id: string;
  dependent_id: string;
}

export interface ContactSubmission {
  created_at: Generated<string>;
  email: string;
  id: string;
  message: string;
  name: string;
  page: string;
}

export interface Dependent {
  alt_contact_name: string | null;
  alt_contact_phone: string | null;
  alt_contact_whatsapp_consent: boolean | null;
  created_at: Generated<string>;
  data_protection_consent: boolean | null;
  disability_type: string | null;
  dob: string;
  emergency_medical_consent: boolean | null;
  gp_phone: string | null;
  gp_surgery: string | null;
  has_disability: boolean | null;
  id: string;
  medical_fitness_declaration: boolean | null;
  medical_info: string | null;
  member_id: string;
  name: string;
  photo_consent: boolean | null;
  play_cricket_id: string | null;
  played_before: boolean | null;
  previous_cricket: string | null;
  school_year: string | null;
  sex: string;
  user_id: string | null;
  whatsapp_consent: boolean | null;
}

export interface EventSubscriber {
  email: string;
  id: string;
  meta: Json;
}

export interface FantasyChaosWeek {
  created_at: Generated<string>;
  description: string;
  email_sent: Generated<boolean>;
  gameweek_id: number;
  id: Generated<number>;
  name: string;
  rule_config: Generated<string>;
  rule_type: string;
  season: string;
  send_email: Generated<boolean>;
}

export interface FantasyChipUsage {
  chip_type: string;
  created_at: Generated<string>;
  fantasy_team_id: number;
  gameweek_id: number;
  id: Generated<number>;
  season: string;
}

export interface FantasyPlayer {
  created_at: Generated<string>;
  eligible: Generated<boolean>;
  play_cricket_id: string;
  player_name: string;
  sandwich_cost: Generated<number>;
}

export interface FantasyPlayerScore {
  batting_points: Generated<number>;
  bowling_points: Generated<number>;
  catches: Generated<number>;
  created_at: Generated<string>;
  fielding_points: Generated<number>;
  gameweek_id: number;
  id: Generated<number>;
  is_actual_keeper: Generated<boolean>;
  match_id: string;
  play_cricket_id: string;
  season: string;
  stumpings: Generated<number>;
  team_points: Generated<number>;
  total_points: Generated<number>;
}

export interface FantasyTeam {
  created_at: Generated<string>;
  id: Generated<number>;
  season: string;
  user_id: string;
}

export interface FantasyTeamPlayer {
  fantasy_team_id: number;
  gameweek_added: number;
  gameweek_removed: number | null;
  id: Generated<number>;
  is_captain: Generated<boolean>;
  is_wicketkeeper: Generated<boolean>;
  play_cricket_id: string;
  slot_type: Generated<string>;
}

export interface FantasyTeamScore {
  created_at: Generated<string>;
  fantasy_team_id: number;
  gameweek_id: number;
  id: Generated<number>;
  season: string;
  total_points: Generated<number>;
}

export interface GameScore {
  best_streak: number;
  catches: number;
  game: Generated<string>;
  id: string;
  level: number;
  score: number;
  updated_at: string;
  user_id: string;
}

export interface GameSponsorship {
  amount_pence: number;
  approved: Generated<boolean>;
  created_at: Generated<string>;
  display_name: string | null;
  game_id: string;
  id: string;
  notes: string | null;
  paid_at: string | null;
  sponsor_email: string;
  sponsor_logo_url: string | null;
  sponsor_message: string | null;
  sponsor_name: string;
  sponsor_website: string | null;
  stripe_payment_intent_id: string | null;
}

export interface JuniorTeam {
  age_group: string;
  created_at: Generated<string>;
  id: string;
  name: string;
  sex: string;
}

export interface JuniorTeamManager {
  junior_team_id: string;
  user_id: string;
}

export interface Matchday {
  competition_type: string | null;
  confirmed_at: string | null;
  confirmed_by: string | null;
  created_at: Generated<string>;
  created_by: string;
  finished_at: string | null;
  finished_by: string | null;
  id: string;
  match_date: string;
  opposition: string;
  play_cricket_match_id: string | null;
  play_cricket_team_id: string;
  status: Generated<string>;
}

export interface MatchdayExpense {
  amount_pence: number;
  approved_at: string | null;
  approved_by: string | null;
  created_at: Generated<string>;
  created_by: string;
  description: string | null;
  expense_type: string;
  id: string;
  matchday_id: string;
  receipt_image_url: string | null;
  reimbursed_at: string | null;
  reimbursed_by: string | null;
  rejected_reason: string | null;
  status: Generated<string>;
  submitted_at: string | null;
}

export interface MatchdayPlayer {
  charge_id: string | null;
  created_at: Generated<string>;
  id: string;
  matchday_id: string;
  member_id: string | null;
  player_name: string;
  replaced_by_matchday_player_id: string | null;
  status: Generated<string>;
}

export interface MatchFeeRate {
  amount_pence: number;
  competition_type: string | null;
  created_at: Generated<string>;
  id: string;
  member_category: string;
  play_cricket_team_id: string | null;
}

export interface MatchPerformanceBatting {
  balls: Generated<number>;
  competition_type: Generated<string>;
  created_at: Generated<string>;
  fours: Generated<number>;
  how_out: Generated<string>;
  id: string;
  match_date: string;
  match_id: string;
  not_out: Generated<boolean>;
  player_id: string;
  player_name: string;
  runs: Generated<number>;
  season: number;
  sixes: Generated<number>;
  team_id: string;
}

export interface MatchPerformanceBowling {
  competition_type: Generated<string>;
  created_at: Generated<string>;
  id: string;
  maidens: Generated<number>;
  match_date: string;
  match_id: string;
  no_balls: Generated<number>;
  overs: Generated<string>;
  player_id: string;
  player_name: string;
  runs: Generated<number>;
  season: number;
  team_id: string;
  wickets: Generated<number>;
  wides: Generated<number>;
}

export interface MatchPerformanceFielding {
  catches: Generated<number>;
  competition_type: Generated<string>;
  created_at: Generated<string>;
  id: string;
  is_wicketkeeper: Generated<boolean>;
  match_date: string;
  match_id: string;
  player_id: string;
  player_name: string;
  run_outs: Generated<number>;
  season: number;
  stumpings: Generated<number>;
  team_id: string;
}

export interface MatchResult {
  away_team_id: string;
  away_team_name: string;
  competition_type: Generated<string>;
  created_at: Generated<string>;
  home_team_id: string;
  home_team_name: string;
  id: string;
  match_date: string;
  match_id: string;
  result: Generated<string>;
  result_applied_to: Generated<string>;
  result_description: Generated<string>;
  season: number;
}

export interface Member {
  address: string | null;
  deleted_at: string | null;
  deleted_by: string | null;
  deleted_reason: string | null;
  dob: string | null;
  email: string;
  emergency_contact_name: string | null;
  emergency_contact_telephone: string | null;
  id: string;
  member_category: string | null;
  name: string | null;
  play_cricket_id: string | null;
  postcode: string | null;
  slug: string | null;
  stripe_customer_id: string | null;
  telephone: string | null;
  title: string | null;
}

export interface Membership {
  created_at: Generated<string>;
  dependent_id: string | null;
  id: string;
  member_id: string;
  paid_until: string;
  type: string | null;
}

export interface Passkey {
  backedUp: boolean;
  counter: number;
  createdAt: Timestamp | null;
  credentialID: string;
  deviceType: string;
  id: string;
  name: string | null;
  publicKey: string;
  transports: string | null;
  userId: string;
}

export interface PlayCricketMatchCache {
  data: string;
  fetched_at: string;
  match_date: string;
  match_id: string;
}

export interface PlayCricketSyncLog {
  completed_at: string | null;
  errors: string | null;
  id: string;
  matches_processed: Generated<number>;
  season: number;
  started_at: string;
}

export interface PlayCricketTeam {
  created_at: Generated<string>;
  id: string;
  is_junior: Generated<boolean>;
  last_updated: string | null;
  name: string;
  site_id: string;
}

export interface PlayerSponsorship {
  amount_pence: number;
  approved: Generated<boolean>;
  created_at: Generated<string>;
  display_name: string | null;
  id: string;
  notes: string | null;
  paid_at: string | null;
  player_name: string;
  season: number;
  slug: string | null;
  sponsor_email: string;
  sponsor_logo_url: string | null;
  sponsor_message: string | null;
  sponsor_name: string;
  sponsor_website: string | null;
  stripe_payment_intent_id: string | null;
}

export interface Session {
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface TeamOfficial {
  play_cricket_team_id: string;
  user_id: string;
}

export interface TwoFactor {
  backupCodes: string;
  id: string;
  secret: string;
  userId: string;
}

export interface User {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Timestamp;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  role: string | null;
  twoFactorEnabled: boolean | null;
  updatedAt: Timestamp;
}

export interface Verification {
  createdAt: Timestamp | null;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Timestamp | null;
  value: string;
}

export interface DB {
  account: Account;
  availability_assignment: AvailabilityAssignment;
  availability_fixture: AvailabilityFixture;
  availability_request: AvailabilityRequest;
  availability_response: AvailabilityResponse;
  charge: Charge;
  charge_dependent: ChargeDependent;
  contact_submission: ContactSubmission;
  dependent: Dependent;
  event_subscriber: EventSubscriber;
  fantasy_chaos_week: FantasyChaosWeek;
  fantasy_chip_usage: FantasyChipUsage;
  fantasy_player: FantasyPlayer;
  fantasy_player_score: FantasyPlayerScore;
  fantasy_team: FantasyTeam;
  fantasy_team_player: FantasyTeamPlayer;
  fantasy_team_score: FantasyTeamScore;
  game_score: GameScore;
  game_sponsorship: GameSponsorship;
  junior_team: JuniorTeam;
  junior_team_manager: JuniorTeamManager;
  match_fee_rate: MatchFeeRate;
  match_performance_batting: MatchPerformanceBatting;
  match_performance_bowling: MatchPerformanceBowling;
  match_performance_fielding: MatchPerformanceFielding;
  match_result: MatchResult;
  matchday: Matchday;
  matchday_expense: MatchdayExpense;
  matchday_player: MatchdayPlayer;
  member: Member;
  membership: Membership;
  passkey: Passkey;
  play_cricket_match_cache: PlayCricketMatchCache;
  play_cricket_sync_log: PlayCricketSyncLog;
  play_cricket_team: PlayCricketTeam;
  player_sponsorship: PlayerSponsorship;
  session: Session;
  team_official: TeamOfficial;
  twoFactor: TwoFactor;
  user: User;
  verification: Verification;
}
