/**
 * Typed API client for the matchday app.
 *
 * Generated from the shared OpenAPI spec (regenerated by the root
 * `openapi:generate` script). Use with react-query exactly like apps/web:
 *
 * ```ts
 * import { api, callApi } from "@/lib/api-client";
 *
 * const { data } = useQuery({
 *   queryKey: ["availability", "active"],
 *   queryFn: () => callApi(api.GET("/api/availability/active")),
 * });
 * ```
 */

import createClient from "openapi-fetch";
import type { paths } from "./api.gen.js";
import { PER_USER_RUNTIME_CACHES } from "./auth-client.js";

/**
 * Resolve the 200 application/json body for a path + method to its
 * generated TS type, e.g.:
 *
 *   type Games = ApiResponse<"/api/games">;
 *   type Game = Games[number];
 *
 * Lifted from apps/web so consumers don't reinvent the shape-casting
 * dance (which is how `home.tsx` ended up reading `data.games` from a
 * response that's an array — silently undefined, silently empty).
 */
export type ApiResponse<P extends keyof paths, M extends string = "get"> =
  paths[P] extends Record<
    M,
    { responses: { 200: { content: { "application/json": infer R } } } }
  >
    ? R
    : never;

/**
 * Pull a human-readable message out of openapi-fetch's `error` slot. The
 * Fastify error handler in apps/api/src/app.ts replies with
 * `{ error: <message> }`, but the legacy shape `{ message: <...> }` shows
 * up too (e.g. better-auth, validation plugins). Bare strings are sent by
 * a few hand-rolled error paths. Anything else falls back to the HTTP
 * status text so the user at least sees something useful.
 */
function extractErrorMessage(error: unknown, fallback: string): string {
  if (typeof error === "string") return error;
  if (typeof error === "object" && error !== null) {
    if ("error" in error && typeof error.error === "string") return error.error;
    if ("message" in error) return String(error.message);
  }
  return fallback;
}

class ApiError extends Error {
  constructor(
    public status: number,
    message: string,
  ) {
    super(message);
    this.name = "ApiError";
  }
}

export const API_BASE =
  (import.meta.env.VITE_API_URL as string | undefined) ?? "/api";

export const api = createClient<paths>({
  baseUrl: API_BASE.replace(/\/api$/, ""),
  credentials: "include",
});

export async function callApi<T>(
  response: Promise<{ data?: T; error?: unknown; response: Response }>,
): Promise<T> {
  const { data, error, response: res } = await response;
  if (error !== undefined) {
    if (res.status === 401) {
      // Session expired server-side without an explicit sign-out — any
      // entry the SW already cached for this URL would otherwise keep
      // serving the previous user's body on the next paint. Drop the
      // specific cache entry now; the next navigation will reach
      // <RequireAuth />, see no session, and bounce to the main site
      // for sign-in.
      void evictResponseFromRuntimeCaches(res.url);
    }
    throw new ApiError(res.status, extractErrorMessage(error, res.statusText));
  }
  return data as T;
}

/**
 * Best-effort delete of `url` from every runtime cache. Used to flush
 * stale authenticated responses when the server returns 401.
 */
async function evictResponseFromRuntimeCaches(url: string): Promise<void> {
  if (typeof caches === "undefined" || !url) return;
  await Promise.all(
    PER_USER_RUNTIME_CACHES.map(async (name) => {
      try {
        const cache = await caches.open(name);
        await cache.delete(url);
      } catch {
        // ignore — Safari private mode can throw here; the next sign-in
        // path will clear caches in bulk via ensureCachesMatchUser.
      }
    }),
  );
}
