/**
 * Typed API client for the matchday app.
 *
 * Generated from the shared OpenAPI spec (regenerated by the root
 * `openapi:generate` script). Use with react-query exactly like apps/web:
 *
 * ```ts
 * import { api, callApi } from "@/lib/api-client";
 *
 * const { data } = useQuery({
 *   queryKey: ["availability", "active"],
 *   queryFn: () => callApi(api.GET("/api/availability/active")),
 * });
 * ```
 */

import createClient from "openapi-fetch";
import type { paths } from "./api.gen.js";

class ApiError extends Error {
  constructor(
    public status: number,
    message: string,
  ) {
    super(message);
    this.name = "ApiError";
  }
}

export const API_BASE =
  (import.meta.env.VITE_API_URL as string | undefined) ?? "/api";

export const api = createClient<paths>({
  baseUrl: API_BASE.replace(/\/api$/, ""),
  credentials: "include",
});

export async function callApi<T>(
  response: Promise<{ data?: T; error?: unknown; response: Response }>,
): Promise<T> {
  const { data, error, response: res } = await response;
  if (error !== undefined) {
    throw new ApiError(
      res.status,
      typeof error === "string"
        ? error
        : typeof error === "object" && error !== null && "message" in error
          ? String(error.message)
          : res.statusText,
    );
  }
  return data as T;
}
