/**
 * Typed API client for the matchday app.
 *
 * Generated from the shared OpenAPI spec (regenerated by the root
 * `openapi:generate` script). Use with react-query exactly like apps/web:
 *
 * ```ts
 * import { api, callApi } from "@/lib/api-client";
 *
 * const { data } = useQuery({
 *   queryKey: ["availability", "active"],
 *   queryFn: () => callApi(api.GET("/api/availability/active")),
 * });
 * ```
 */

import createClient from "openapi-fetch";
import type { paths } from "./api.gen.js";

/**
 * Resolve the 200 application/json body for a path + method to its
 * generated TS type, e.g.:
 *
 *   type Games = ApiResponse<"/api/games">;
 *   type Game = Games[number];
 *
 * Lifted from apps/web so consumers don't reinvent the shape-casting
 * dance (which is how `home.tsx` ended up reading `data.games` from a
 * response that's an array — silently undefined, silently empty).
 */
export type ApiResponse<
  P extends keyof paths,
  M extends string = "get",
> = paths[P] extends Record<
  M,
  { responses: { 200: { content: { "application/json": infer R } } } }
>
  ? R
  : never;

class ApiError extends Error {
  constructor(
    public status: number,
    message: string,
  ) {
    super(message);
    this.name = "ApiError";
  }
}

export const API_BASE =
  (import.meta.env.VITE_API_URL as string | undefined) ?? "/api";

export const api = createClient<paths>({
  baseUrl: API_BASE.replace(/\/api$/, ""),
  credentials: "include",
});

export async function callApi<T>(
  response: Promise<{ data?: T; error?: unknown; response: Response }>,
): Promise<T> {
  const { data, error, response: res } = await response;
  if (error !== undefined) {
    throw new ApiError(
      res.status,
      typeof error === "string"
        ? error
        : typeof error === "object" && error !== null && "message" in error
          ? String(error.message)
          : res.statusText,
    );
  }
  return data as T;
}
